### PR TITLE
Update style_detection.py

### PR DESCRIPTION
**Pull request by rzeydelis**
fix regex statement

### CODE REVIEW

**Comment by john-friedman** [comment]
Hey Bobby, nice catch. I'll merge it later today.

**Comment by john-friedman** [comment]
Did it affect anything for you before the change?

**Comment by rzeydelis** [comment]
No, it was just throwing a warning.

**Comment by john-friedman** [comment]
Ah great! In that case I'll hold off on the update to pip for a bit. Btw, I would love to know what you're working on.

**Pull request merged**
